---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: openlookeng-website
spec:
  replicas: 6
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: websiteinfo
  template:
    metadata:
      labels:
        app: websiteinfo
    spec:
      containers:
      - name: websitepod
        image: opensourceway/openlookeng_website:0.1
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
