resources:
- deployment.yaml
- namespace.yaml
- service.yaml
commonLabels:
  app: openlookeng-website
namespace: website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/openlookeng_website
  newTag: 2ec6df0ee445e2d2495bf4e825a9b6706791a1f7
