resources:
- deployment.yaml
- namespace.yaml
- service.yaml
commonLabels:
  app: openlookeng-website
namespace: website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/openlookeng_website
  newTag: eea5d1f503773a176c4f5a20938029dc65e6ee7b
