resources:
- deployment.yaml
- namespace.yaml
- service.yaml
- purge-cache.yaml
- purge-secrets.yaml
commonLabels:
  app: openlookeng-website
namespace: website
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: opensourceway/openlookeng_website
  newTag: a2a58f65b1ad40ffce4ee8f1530ec429823d31d1
