# Config web service
---
apiVersion: v1
kind: Service
metadata:
  name: websiteservice
spec:
  ports:
    - name: httpport
      protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31110
  selector:
    app: websiteinfo
  type: NodePort
