resources:
  - deployment.yaml
  - namespace.yaml
  - service.yaml
  - secrets.yaml
commonLabels:
  app: openlookeng-bot
commonAnnotations:
  owner: chenzeng
  email: "chenzeng765@163.com"
namespace: bot


