---
apiVersion: v1
kind: Service
metadata:
  name: botservice
  namespace: bot
spec:
  ports:
    - name: httpport
      protocol: TCP
      port: 80
      targetPort: 8888
      nodePort: 31202
  selector:
    app: botinfo
  type: NodePort
