resources:
  - config.yaml
  - mailcore.yaml
  - mailcoreservice.yaml
  - maildatabase.yaml
  - mtaservice.yaml
  - namespace.yaml
  - nginx-config.yaml
  - secrets.yaml
  - storage.yaml
  - suiteservice.yaml
  - webservice.yaml
namespace: mail
