resources:
  - https://github.com/opensourceways/app-jenkins/deploy-without-agent?ref=stable
  - secrets.yaml
  - namespace.yaml
commonLabels:
  app: openlookeng-jenkins
  owner: chenzeng
commonAnnotations:
  email: "chenzeng2@huawei.com"
patchesStrategicMerge:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
namespace: jenkins
