---
apiVersion: secrets-manager.tuenti.io/v1alpha1
kind: SecretDefinition
metadata:
  name: openlookeng-jenkins
spec:
  name: openlookeng-jenkins
  keysMap:
    jenkins-admin-user:
      path: secrets/data/openlookeng/jenkins
      key: jenkins-admin-user
    jenkins-admin-password:
      path: secrets/data/openlookeng/jenkins
      key: jenkins-admin-password
