apiVersion: v1
kind: Service
metadata:
  name: jenkins
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
      # We pinned NodePort to fix number in order to used NodePort service
      nodePort: 32717
  loadBalancerSourceRanges:
  type: NodePort