# Resource for centos specification slave pods
apiVersion: v1
kind: Service
metadata:
  name: x86-centos-slaves-service
  labels:
    app: x86-centos-slaves
spec:
  ports:
    - port: 80
      name: port-placeholder
  clusterIP: None
  selector:
    app: x86-centos-slaves

---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: x86-centos-slaves
  labels:
    app: x86-centos-slaves
spec:
  serviceName: x86-centos-slaves-service
  replicas: 4
  selector:
    matchLabels:
      app: x86-centos-slaves
  template:
    metadata:
      labels:
        app: x86-centos-slaves
    spec:
      securityContext:
        fsGroup: 995
      initContainers:
        - name: slave-init
          image: swr.cn-north-1.myhuaweicloud.com/mindspore/jenkins-slave-tools:0.0.1
          volumeMounts:
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
          env:
            - name: JENKINS_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_USER_NAME
              valueFrom:
                secretKeyRef:
                  name: openlookeng-jenkins
                  key: jenkins-admin-user
            - name: JENKINS_USER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: openlookeng-jenkins
                  key: jenkins-admin-token
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
            - name: EXECUTOR_NUMBERS
              value: "1"
            - name: NODE_LABELS
              value: x86 centos
            - name: JENKINS_SHARE_FOLDER
              value: /home/jenkins/share-config
          args: ["$(JENKINS_URL)", "$(JENKINS_USER_NAME)", "$(JENKINS_USER_PASSWORD)", "$(JENKINS_NODE_NAME)", "$(EXECUTOR_NUMBERS)", "$(JENKINS_AGENT_WORKDIR)", "$(NODE_LABELS)", "$(JENKINS_SHARE_FOLDER)"]
      containers:
        - name: jenkins-slave
          image: opensourceway/openhetu-centos-slave:0.0.2
          imagePullPolicy: "IfNotPresent"
          volumeMounts:
            - mountPath: /home/jenkins/agent-working-dir
              name: centos-workspace-pvc
            - mountPath: /home/jenkins/share-config
              name: jenkins-share-config
            - mountPath: /var/run/docker.sock
              name: docker-socket
          command:
            - /bin/sh
            - -c
            - |
              export JENKINS_SECRET=`cat /home/jenkins/share-config/node_secret.id`;
              exec jenkins-agent
          resources:
            requests:
              cpu: 14000m
              memory: 100000Mi
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: JENKINS_TUNNEL
              value: jenkins-agent.jenkins.svc.cluster.local:50000
            - name: JENKINS_AGENT_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: JENKINS_AGENT_WORKDIR
              value: /home/jenkins/agent-working-dir
            - name: JENKINS_URL
              value: http://jenkins.jenkins.svc.cluster.local
      volumes:
        - name: jenkins-share-config
          emptyDir: {}
        - name: docker-socket
          hostPath:
            path: /var/run/docker.sock
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: centos-workspace-pvc
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 100Gi
        storageClassName: csi-disk
