resources:
  - https://github.com/opensourceways/app-repo/deploy?ref=stable
  - pvc.yaml
  - namespace.yaml
  - secrets.yaml
commonLabels:
  app: openlookeng-hk-repo
  owner: chenzeng
commonAnnotations:
  email: "chenzeng2@huawei.com"
patchesStrategicMerge:
  - configmap.yaml
  - deployment.yaml
  - service.yaml
patchesJson6902:
  - target:
      group: ""
      version: v1
      kind: Service
      name: repo-service
    path: selector.yaml
namespace: repo


