---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: openlookeng-data-volume
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
  storageClassName: csi-disk