---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: jenkins
spec:
  template:
    spec:
      imagePullSecrets:
      - name: huawei-swr-image-pull-secret
      containers:
        - name: jenkins
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins:lts
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: openlookeng-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: openlookeng-jenkins
          resources:
            requests:
              cpu: 2000m
              memory: 2000Mi
            limits:
              cpu: 12000m
              memory: 32000Mi
      initContainers:
        - name: copy-default-config
          image: swr.cn-north-4.myhuaweicloud.com/opensourceway/common/jenkins:lts
          env:
            - name: ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-password
                  name: openlookeng-jenkins
            - name: ADMIN_USER
              valueFrom:
                secretKeyRef:
                  key: jenkins-admin-user
                  name: openlookeng-jenkins
      volumes:
        - name: jenkins-home
          persistentVolumeClaim:
            claimName: jenkins
