resources:
  - https://github.com/opensourceways/app-jenkins/deploy-without-agent?ref=stable
  - secrets.yaml
  - namespace.yaml
  - ingress.yaml
commonLabels:
  app: openlookeng-jenkins
commonAnnotations:
  owner: chenzeng
  email: "chenzeng765@163.com"
patchesStrategicMerge:
  - pvc.yaml
  - deployment.yaml
  - service.yaml
namespace: jenkins-test
